### ISSUE TITLE
Editor Mode + GPU Instancing in a Preview Viewport Not working

### ISSUE THREAD

**Issue by cp-stone-henrik** [CyberAgentGameEntertainment/NovaShader#67] opened 2023-12-13 11:08 UTC
The positioning of particles that are using GPU Instancing are not getting repositioned to their correct position when running manual ParticleSystem Simulation inside of a custom PreviewUtility created viewport through an Editor Script.
There are no Problems in ordinary execution or with Unity's own Editor side simulation features.

**Comment by CyTakayukiKiyohara** [comment] 2024-03-13 01:25
Thank you for reporting the problem.
We are currently investigating this issue.
Please give us a little time.

**Comment by CA-Tatami** [comment] 2024-03-21 09:01
@cp-stone-henrik 
Regarding the issue you reported, we are having difficulty preparing an environment for reproduction, and are thus unable to investigate the cause. If you could provide a project in which the issue can be reproduced, we will conduct a detailed investigation.

**Comment by cp-stone-henrik** [comment] 2024-03-21 09:04
@CA-Tatami 
I understand. I will see if I can prepare a simple environment where it is reproducible.

**Comment by cp-stone-henrik** [comment] 2024-03-22 03:23
@CA-Tatami

I have distilled it down to a simple unitypackage but the project setting might need to be applied correctly.
The window opened through the menu CustomRenderParticle->Open should display the Mesh particles in the same way as the red checkmark particles but it does not displace them correctly when used with the `Enable Mesh GPU Instancing` enabled.

[NovaShaderRenderBugPackage.zip](https://github.com/CyberAgentGameEntertainment/NovaShader/files/14716888/NovaShaderRenderBugPackage.zip)

**Comment by CA-Tatami** [comment] 2024-03-22 09:44
Thank you for your cooperation.
We will conduct an investigation based on the information you provided.

**Comment by CA-Tatami** [comment] 2024-03-26 08:07
@cp-stone-henrik 
We have investigated the following three shaders and have confirmed the reported defects in all of them.

- NOVA Shader
- Sample shader using Custom Vertex Stream without NOVA Shader
- Unity's official Particle shader (Universal Render Pipeline/Particle/Unlit)

This indicates that the problem is not specific to the NOVA Shader, but is most likely caused on the Unity side.
Therefore, we have added a note to the documentation and reported the issue to Unity.
I would like to close this issue now.

**Closed by CA-Tatami** 2024-03-26 08:07 UTC

**Comment by CA-Tatami** [comment] 2024-04-30 00:53
@cp-stone-henrik
This is the above report, but I received the following communication from Unity.
It does not look like it will be fixed, at least in the near future.

`Won't Fix for Branch:Closed at 2023.2. Resolved by George Karmiris Resolution note: Closed as resolved. Won't be fixed because 2023.2 has reached EOL.`

**Comment by CA-Tatami** [comment] 2024-05-07 01:10
I received an additional communication with the following information. “GPU instances are not supported by the URP preview camera.”
